### PR TITLE
Cleanup and refactoring of termistor LUT generator (fixes bug #1305)

### PR DESCRIPTION
**Pull request by stv0g**
Results have been compared/validated with the existing script.

    ./createTemperatureLookupMarlin.py --rp=10000 --t1=25:1000000 --t2=150:1454 --t3=285:149

Will yield a negative C/C3 Steinhart-Hard coefficient which is somehow abnormal.
A warning message will be shown and the coefficient will be ignored
I've applied the workaround proposed by @gaby64.

### CODE REVIEW

**Comment by stv0g** [comment]
Feel free to postpone this patch for the next milestone :smile:

**Comment by stv0g** [comment]
thanks :-)

**Comment by boelle** [comment]
np... i thought why not include all the fix's we can.... i wish just that
the last issue on milestone 1 could be fixed also

me not good at coding.... i'm just the resident house elf :-D

2015-01-06 11:29 GMT+01:00 Steffen Vogel <notifications@github.com>:

**Comment by stv0g** [comment]
I'm really happy that this project finally found someone who cares and manages.
Thumbs up for your work. Thank you :-)

I'll try to keep you busy :p

**Comment by boelle** [comment]
heheh... np

and sorry if i'm a bit fast to close things... want to keep the list as short as possible

if you are bored try to have a go at this one: https://github.com/ErikZalm/Marlin/issues/416

:+1:

**Pull request merged**
