### PR TITLE
issue 968 rebased for dev branch

### PR DESCRIPTION
**Pull request by i-make-robots**
- added max_ok_timeout to prevent print hangs

### CODE REVIEW

**Comment by boelle** [comment]
this one has hanged arround a long time..

2 reasons for closing without merge

1. the pull request is made to v1 branch which is no longer here
2. it does not allow automatic merge

**Comment by i-make-robots** [comment]
Is it resubmitting the original pull request?  I'm trying to make a new pull request off the latest dev branch.

**Comment by boelle** [comment]
i think what goes wrong is that you made this on the marlin v1 branch... and the git system will automatic make the pull request against that when you submit one...

the quick and dirty way is to delete marlin from your git and then fork the dev branch and make the changes needed and submit a new pull request... admitted it takes a bit more

i wanted to mark the dev branch the default one but only @ErikZalm can do that but he is very busy at times

**Comment by i-make-robots** [comment]
That's... that's what I did.

On Sun, Jan 4, 2015 at 11:15 AM, Bo Herrmannsen <notifications@github.com>
wrote:

> i think what goes wrong is that you made this on the marlin v1 branch...
> and the git system will automatic make the pull request against that when
> you submit one...
>
> the quick and dirty way is to delete marlin from your git and then fork
> the dev branch and make the changes needed and submit a new pull request...
> admitted it takes a bit more
>
> i wanted to mark the dev branch the default one but only @ErikZalm
> <https://github.com/ErikZalm> can do that but he is very busy at times
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ErikZalm/Marlin/pull/1283#issuecomment-68644783>.
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by boelle** [comment]
at the top i got: "i-make-robots  wants to merge 1 commit into ErikZalm:Marlin_v1 from i-make-robots:Marlin_v1"

**Comment by boelle** [comment]
so something must have gone wrong

**Pull request closed without merging**
