### PR TITLE
Fix for cant compile when REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER ...

### PR DESCRIPTION
**Pull request by wgm4321**
...defined

Adds defines for float43 which is used for the filament menu.

### CODE REVIEW

**Comment by wgm4321** [comment]
@monkeydave, can you try this fix for the compile errors?

I couldn't fully compile the source because I can't get the U8glib to be recognized by the Arduino IDE.   However, I think this addresses the issues I introduced.

**Comment by monkeydave** [comment]
Marlin now compiles when REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER is defined

I have tested this with my Azteeg X3 Pro board and reprap discount full lcd, after merging in the latest Development branch as @wgm4321 Development branch isn't upto date. It compiled successfully and uploaded successfully to my board.

**Comment by boelle** [comment]
dev branch is up to date.... we just cant merge all pull requests... some
direct fail the CI build and some cant be merged automatic...

2015-01-04 0:53 GMT+01:00 monkeydave <notifications@github.com>:

**Comment by boelle** [comment]
oh you meant this one was not merged... it will be now.. we are not always fast as lightning

**Comment by alexborro** [comment]
Ok and what about all other LCDs like Viki? We need to take care when
adding something that can mess other stuffs.

Otherwise many people will have they firmware broken when upgrading to a
latest version.
Em 03/01/2015 22:29, "Bo Herrmannsen" <notifications@github.com> escreveu:

**Comment by wgm4321** [comment]
@alexborro My changes were new float43 versions derived from the float32 references in ultralcd.cpp.

It seems that each controller must implement these routines.   So I searched for all references to float32 and made sure that there was a float43 version on the assumption that if float32 was referenced, a compiler error would occur if the float43 form didn't exist.

There was only one other definition for float32 that didn't have a float43 and that was in dogm_lcd_implementation.h.

So where there was just:
#define lcd_implementation_drawmenu_setting_edit_float32_selected(row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, '>', ftostr32(*(data)))
#define lcd_implementation_drawmenu_setting_edit_float32(row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, ' ', ftostr32(*(data)))

and

#define lcd_implementation_drawmenu_setting_edit_callback_float32_selected(row, pstr, pstr2, data, minValue, maxValue, callback) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, '>', ftostr32(*(data)))
#define lcd_implementation_drawmenu_setting_edit_callback_float32(row, pstr, pstr2, data, minValue, maxValue, callback) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, ' ', ftostr32(*(data)))

there is now:
#define lcd_implementation_drawmenu_setting_edit_float32_selected(row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, '>', ftostr32(*(data)))
#define lcd_implementation_drawmenu_setting_edit_float32(row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, ' ', ftostr32(*(data)))
#define lcd_implementation_drawmenu_setting_edit_float43_selected(row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, '>', ftostr43(*(data)))
#define lcd_implementation_drawmenu_setting_edit_float43(row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, ' ', ftostr43(*(data)))

and 

#define lcd_implementation_drawmenu_setting_edit_callback_float32_selected(row, pstr, pstr2, data, minValue, maxValue, callback) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, '>', ftostr32(*(data)))
#define lcd_implementation_drawmenu_setting_edit_callback_float32(row, pstr, pstr2, data, minValue, maxValue, callback) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, ' ', ftostr32(*(data)))
#define lcd_implementation_drawmenu_setting_edit_callback_float43_selected(row, pstr, pstr2, data, minValue, maxValue, callback) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, '>', ftostr43(*(data)))
#define lcd_implementation_drawmenu_setting_edit_callback_float43(row, pstr, pstr2, data, minValue, maxValue, callback) lcd_implementation_drawmenu_setting_edit_generic(row, pstr, ' ', ftostr43(*(data)))

Hopefully, that catches all other LCDs.   

Let me know if you think this isn't sufficient.

**Comment by monkeydave** [comment]
@alexborro 
See my PR #1304 this checks compile for most of the LCD's now with Travis CI, some need extra hardware files added and can't be automatically checked yet.
I think the only LCD I haven't been able to compile with yet is SAV_3DLCD but I haven't really looked into it yet either.

**Pull request merged**
