### PR TITLE
Readd .travis.yml

### PR DESCRIPTION
**Pull request by monkeydave**
This file was removed in commit 95429a4108775f319bbe0b853c6fef711580e30a 

At the moment the Travis-Ci build passing image points to a build from 5 days ago as there is no longer a .travis.yml file in the repo.

This file isn't the same as the one removed the other day, I have changed the travis.yml file to use ino the command line compiler for Arduino as I couldn't easily get the Makefile to work with the U8glib library so I decided to use ino instead.

It should now be easy to add commands to the script: part of the travis.yml file and check compilation with different boards and with extra options defined in Configuration.h and Configuration_adv.h whch will hopefully create a more stable Marlin going forward. The previous travis.yml file only checked the default config with an ultimaker board, its never going to pick up most of the compile errors when people are adding in stuff that doesn't get compiled in automatically with the default configuration.

Check https://travis-ci.org/monkeydave/Marlin/builds for the build history of my branch as it will fail at the moment because I had to change the directory to ErikZalm so it will compile when/if it is merged.

I am happy to add more compile options but didn't want to waste my time if this doesn't get merged in.

### CODE REVIEW

**Comment by boelle** [comment]
So for me the house elf that means that travis can now check more than one config... in the end avoiding to long testing rounds?

**Comment by boelle** [comment]
if i get it right i'm to blame again for its removal....  we do have a list of testers and what hardware they use so could have it check against those ? their test will just be an extra check and we can reduce test time from dev to stable to say 1 month or less maybe

**Comment by monkeydave** [comment]
New features will still need to be tested to check they still work as the developer intended. This only checks that Marlin builds successfully but we can add as many different configurations as we like.

**Comment by boelle** [comment]
of course new stuff will have to be tested.... but non the less this will take some load of testers and we have an idea if a new feature will break more than it adds

so merging this one...

**Comment by monkeydave** [comment]
Ok I will add more configurations to the travis.yml file and submit another pull request, probably tomorrow before I get around to it.

**Comment by boelle** [comment]
no rush, we all work on this for fun 😄

Den lørdag den 3. januar 2015 skrev monkeydave <notifications@github.com>:

**Comment by alexborro** [comment]
Thanks @monkeydave ,  automatic compilation tests are ALWAYS welcome. 

If you have more free time, please, add more tests. It will help us all making a more stable Marlin. 

Cheers. 

Alex.

**Pull request merged**
