### PR TITLE
Added .gitignore back into repo

### PR DESCRIPTION
**Pull request by monkeydave**
The .gitignore file was removed with commit 60959f196f291787ae6ee15344a32124e5aefad7, just adding it back in.

### CODE REVIEW

**Comment by orangeudav** [comment]
Please, add .idea and .DS_Store

**Comment by alexborro** [comment]
Sorry my ignorance in git stuffs, what are these files meant for?
Em 03/01/2015 09:09, "orangeudav" <notifications@github.com> escreveu:

**Comment by orangeudav** [comment]
.idea/ folder is project folder for Eclipse-family IDEs
.DS_Store is a hidden file with a proprietary format created by OS X to store custom attributes of a folder such as the position of icons or the choice of a background image.(from wiki)

**Comment by boelle** [comment]
so they are not a part needed for marlin?

our goal here is to have as few files while not breaking things

this is really support for 3rd party stuff

closing

**Comment by boelle** [comment]
to make it clear.... we want to add support for hardware of course... the idea is that people can just grab marlin and load it on to the board.... if a given IDE does not support the hardware out the box then the files needed for that should be there...

but support for an given IDE be it arduino IDE or eclipse etc etc... no, if we have to do that it will be a slide and we end up adding things that does not have to do with marlin

what IDE the user choose is the users problem... not our as collabs/dev people...

same goes for what OS people use... we have enough on our hands with just the firmware... 

and again we will just clutter up the repro more than need be

and we can do perfectly well without the .gitignore file, as long we dont add un-needed files in the repro or local when fixing bugs and we do pull requests... ie dont add .bak files etc...

**Comment by monkeydave** [comment]
This file is not used in marlin but will save developers from checking in garbage build files and other temporary files from their text editors.

**Comment by boelle** [comment]
it has never been a problem for me

but i also check that i dont save temp files within the dir i work on.

just gone out to fill car with fresh oil

is the ignore files stuffed with the right extensions etc ?

Den lørdag den 3. januar 2015 skrev monkeydave <notifications@github.com>:

**Comment by boelle** [comment]
i mean its an old one so might not be updated etc.. those hidden apple
files etc

Den lørdag den 3. januar 2015 skrev monkeydave <notifications@github.com>:

**Comment by boelle** [comment]
added... saw that the hidden apple files are not ignored will add them now

**Pull request merged**
